// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tests.DataAccess;

#nullable disable

namespace Tests.DataAccess.Migrations
{
    [DbContext(typeof(TestsAppDbContext))]
    [Migration("20250115095851_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AnimalsDb")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("PersonSequence");

            modelBuilder.HasSequence("PetSequence");

            modelBuilder.Entity("Tests.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"AnimalsDb\".\"PersonSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People", "AnimalsDb");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Tests.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"AnimalsDb\".\"PetSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Tests.Entities.Cat", b =>
                {
                    b.HasBaseType("Tests.Entities.Pet");

                    b.Property<bool>("LovesSleeping")
                        .HasColumnType("boolean");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cats", "AnimalsDb");
                });

            modelBuilder.Entity("Tests.Entities.Dog", b =>
                {
                    b.HasBaseType("Tests.Entities.Pet");

                    b.Property<bool>("LovesChasingSticks")
                        .HasColumnType("boolean");

                    b.HasIndex("OwnerId");

                    b.ToTable("Dogs", "AnimalsDb");
                });

            modelBuilder.Entity("Tests.Entities.Cat", b =>
                {
                    b.HasOne("Tests.Entities.Person", "Owner")
                        .WithMany("Cats")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Tests.Entities.Dog", b =>
                {
                    b.HasOne("Tests.Entities.Person", "Owner")
                        .WithMany("Dogs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Tests.Entities.Person", b =>
                {
                    b.Navigation("Cats");

                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
